# Generated by Django 4.0.2 on 2022-02-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin', '0002_alter_covid_date_alter_covid_deathcnt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covid',
            name='date',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
