# Generated by Django 4.0.2 on 2022-02-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin', '0003_alter_covid_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='covid',
            name='intdate',
            field=models.IntegerField(default=0),
        ),
    ]
